spring:
  application:
    name: Petory

  profiles:
    active:
      - local
  config:
    import: classpath:/config/application-prod.yml
---
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jwt:
    secret: bucksbunny
    expiredAt:
      ATK: 86400000
    #1초 * 60 = 1분 * 60 = 1시간 * 24 = 하루
      RTK: 604800000
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs/swagger
    url: /docs/open-api-3.0.1.json
  default-consumes-media-type: application/json;charset=UTF-8

